### PR TITLE
Added packaging using CPack

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by burner** [comment]
awesome thank you.

after merging this, do I have to do anything else?

**Comment by KOLANICH** [comment]
You can try to setup GitHub CI to make binary artifacts. Also it is possible to use GitHub Pages to host some repos, so users can add them into their `sources.list` (Though the deb packages generated by CPack are not proper packages (i.e. they lack SHA256 hashes, only MD5 ones are present) , to build proper ones (using the metadata from CMake scripts, whrn CMake is used as a build system) and publish them I have been using my custom software (`prebuilder` it is called) extensively automating the process, but it got broken somewhen and I have no time to fix it currently).

**Comment by burner** [comment]
thank you for the reply, I'll take a look.

I was hoping c++ got its own npmjs.com in the meantime.

**Comment by KOLANICH** [comment]
I hope it will never happen. npm is a flawed package manager plagued with malware. Proper package managers for C and C++ already exist ... they are distro package managers. rpm, dpkg, pacman, conda, software and repos like this one.

**Comment by burner** [comment]
fair point, dlang's code.dlang.org is okay, but its all source build packages, and less popular so less malware

**Pull request merged**
